version: '3'
services:
  arangodb_db_container:
    container_name: arangodb
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: password
    ports:
      - 8529:8529
    volumes:
      - ./arangodb/arangodb_data_container:/var/lib/arangodb3
      - ./arangodb/arangodb_apps_data_container:/var/lib/arangodb3-apps
    restart: always
